// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemRumahMakan.Data;

#nullable disable

namespace SistemRumahMakan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629193141_AddOrder")]
    partial class AddOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemRumahMakan.Models.KategoriMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NamaKategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("KategoriMenus");
                });

            modelBuilder.Entity("SistemRumahMakan.Models.Meja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("int");

                    b.Property<string>("NomorMeja")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mejas");
                });

            modelBuilder.Entity("SistemRumahMakan.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("KategoriMenuId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NamaMenu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriMenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("SistemRumahMakan.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderHeaderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("OrderHeaderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SistemRumahMakan.Models.OrderHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MejaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NomorOrder")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MejaId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("SistemRumahMakan.Models.Menu", b =>
                {
                    b.HasOne("SistemRumahMakan.Models.KategoriMenu", "KategoriMenu")
                        .WithMany("Menus")
                        .HasForeignKey("KategoriMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriMenu");
                });

            modelBuilder.Entity("SistemRumahMakan.Models.OrderDetail", b =>
                {
                    b.HasOne("SistemRumahMakan.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemRumahMakan.Models.OrderHeader", "OrderHeader")
                        .WithMany("Details")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("OrderHeader");
                });

            modelBuilder.Entity("SistemRumahMakan.Models.OrderHeader", b =>
                {
                    b.HasOne("SistemRumahMakan.Models.Meja", "Meja")
                        .WithMany()
                        .HasForeignKey("MejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meja");
                });

            modelBuilder.Entity("SistemRumahMakan.Models.KategoriMenu", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("SistemRumahMakan.Models.OrderHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
